[package]
name = "lab_05"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = "*"
primes = "0.2.3"
rand = "0.7.0"
ring = "*"
hex-literal = "*"
sha2 = "*"
rsa = "0.3.0"